resources:

  - name: choco
    type: git
    source:
      uri: https://github.com/chocolatey/choco

  - name: choco-linux-image
    type: docker-image
    source: { repository: patrickhuber/choco-linux }

  - name: cf-cli-release
    type: github-release
    source:
      owner: cloudfoundry
      repository: cli
      
  - name: cloudfoundry-cli-chocolatey
    type: git
    source:
      uri: https://github.com/patrickhuber/cloudfoundry-cli-chocolatey

jobs:

  - name: build
    plan: 
      - get: choco
      - put: choco-linux-image
        params: 
          build: choco/docker
          dockerfile: Dockerfile.linux

  - name: pack          
    plan:
      - get: choco
        passed: [ build ]
      - get: choco-linux-image
        passed: [ build ]
      - get: cf-cli-release
      - get: cloudfoundry-cli-chocolatey
      - task: run-choco-pack
        image: choco-linux-image
        file: cloudfoundry-cli-chocolatey/ci/pack.yml
