resources:

  - name: choco
    type: git
    source:
      uri: https://github.com/chocolatey/choco.git

  - name: choco-linux-image
    type: docker-image
    source: 
      repository: patrickhuber/choco-linux 
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: cf-cli-release
    type: github-release
    source:
      owner: cloudfoundry
      repository: cli
      access_token: {{github-access-token}}      

  - name: cloudfoundry-cli-chocolatey
    type: git
    source:
      uri: https://github.com/patrickhuber/cloudfoundry-cli-chocolatey.git

jobs:

  - name: build
    plan: 
      - get: choco
      - put: choco-linux-image
        params: 
          build: choco
          dockerfile: choco/docker/Dockerfile.linux

  - name: pack          
    plan:
      - get: choco-linux-image
        passed: [ build ]
      - get: cf-cli-release
        trigger: true
      - get: cloudfoundry-cli-chocolatey
      - task: run-choco-pack
        image: choco-linux-image
        file: cloudfoundry-cli-chocolatey/ci/pack.yml